# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui5.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1268, 823)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_img1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_img1.setFont(font)
        self.label_img1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_img1.setObjectName("label_img1")
        self.verticalLayout.addWidget(self.label_img1)
        self.scrollArea_img1 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_img1.setWidgetResizable(True)
        self.scrollArea_img1.setObjectName("scrollArea_img1")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 299, 337))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.view_img1 = ImageView(self.scrollAreaWidgetContents)
        self.view_img1.setObjectName("view_img1")
        self.gridLayout.addWidget(self.view_img1, 0, 0, 1, 1)
        self.scrollArea_img1.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea_img1)
        self.verticalLayout_10.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_img2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_img2.setFont(font)
        self.label_img2.setObjectName("label_img2")
        self.verticalLayout_3.addWidget(self.label_img2)
        self.scrollArea_img1_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_img1_2.setWidgetResizable(True)
        self.scrollArea_img1_2.setObjectName("scrollArea_img1_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 299, 336))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.view_img2 = ImageView(self.scrollAreaWidgetContents_3)
        self.view_img2.setObjectName("view_img2")
        self.gridLayout_2.addWidget(self.view_img2, 0, 0, 1, 1)
        self.scrollArea_img1_2.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_3.addWidget(self.scrollArea_img1_2)
        self.verticalLayout_10.addLayout(self.verticalLayout_3)
        self.horizontalLayout_9.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.img1_comp = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.img1_comp.setFont(font)
        self.img1_comp.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.img1_comp.setObjectName("img1_comp")
        self.img1_comp.addItem("")
        self.img1_comp.addItem("")
        self.img1_comp.setItemText(1, "Magnitude")
        self.img1_comp.addItem("")
        self.img1_comp.addItem("")
        self.img1_comp.addItem("")
        self.img1_comp.addItem("")
        self.img1_comp.addItem("")
        self.verticalLayout_2.addWidget(self.img1_comp)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 299, 336))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.view_comp1 = ImageView(self.scrollAreaWidgetContents_2)
        self.view_comp1.setObjectName("view_comp1")
        self.gridLayout_4.addWidget(self.view_comp1, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.scrollArea_2)
        self.verticalLayout_11.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.img2_comp = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.img2_comp.setFont(font)
        self.img2_comp.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.img2_comp.setObjectName("img2_comp")
        self.img2_comp.addItem("")
        self.img2_comp.addItem("")
        self.img2_comp.setItemText(1, "Magnitude")
        self.img2_comp.addItem("")
        self.img2_comp.addItem("")
        self.img2_comp.addItem("")
        self.img2_comp.addItem("")
        self.img2_comp.addItem("")
        self.verticalLayout_4.addWidget(self.img2_comp)
        self.scrollArea_img2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_img2.setWidgetResizable(True)
        self.scrollArea_img2.setObjectName("scrollArea_img2")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 299, 335))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.view_comp2 = ImageView(self.scrollAreaWidgetContents_4)
        self.view_comp2.setObjectName("view_comp2")
        self.gridLayout_3.addWidget(self.view_comp2, 0, 0, 1, 1)
        self.scrollArea_img2.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_4.addWidget(self.scrollArea_img2)
        self.verticalLayout_11.addLayout(self.verticalLayout_4)
        self.horizontalLayout_9.addLayout(self.verticalLayout_11)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_9)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_mixer = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_mixer.setFont(font)
        self.label_mixer.setObjectName("label_mixer")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_mixer)
        self.comboBox_out = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_out.setFont(font)
        self.comboBox_out.setObjectName("comboBox_out")
        self.comboBox_out.addItem("")
        self.comboBox_out.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_out)
        self.verticalLayout_9.addLayout(self.formLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_9.addItem(spacerItem)
        self.verticalLayout_14.addLayout(self.verticalLayout_9)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_comp1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_comp1.setFont(font)
        self.label_comp1.setObjectName("label_comp1")
        self.horizontalLayout_4.addWidget(self.label_comp1)
        self.comboBox1_img = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.comboBox1_img.setFont(font)
        self.comboBox1_img.setObjectName("comboBox1_img")
        self.comboBox1_img.addItem("")
        self.comboBox1_img.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox1_img)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.slide1_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.slide1_label.setFont(font)
        self.slide1_label.setObjectName("slide1_label")
        self.horizontalLayout_2.addWidget(self.slide1_label)
        self.Slider1 = QtWidgets.QSlider(self.centralwidget)
        self.Slider1.setMaximum(100)
        self.Slider1.setOrientation(QtCore.Qt.Horizontal)
        self.Slider1.setObjectName("Slider1")
        self.horizontalLayout_2.addWidget(self.Slider1)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        spacerItem2 = QtWidgets.QSpacerItem(128, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.comboBox_comp1 = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_comp1.setFont(font)
        self.comboBox_comp1.setObjectName("comboBox_comp1")
        self.comboBox_comp1.addItem("")
        self.comboBox_comp1.addItem("")
        self.comboBox_comp1.addItem("")
        self.comboBox_comp1.addItem("")
        self.comboBox_comp1.addItem("")
        self.comboBox_comp1.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_comp1)
        self.verticalLayout_7.addLayout(self.formLayout)
        self.verticalLayout_12.addLayout(self.verticalLayout_7)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_12.addItem(spacerItem3)
        self.verticalLayout_14.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_comp2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_comp2.setFont(font)
        self.label_comp2.setObjectName("label_comp2")
        self.horizontalLayout_7.addWidget(self.label_comp2)
        self.comboBox2_img = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.comboBox2_img.setFont(font)
        self.comboBox2_img.setObjectName("comboBox2_img")
        self.comboBox2_img.addItem("")
        self.comboBox2_img.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox2_img)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.slide2_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.slide2_label.setFont(font)
        self.slide2_label.setObjectName("slide2_label")
        self.horizontalLayout.addWidget(self.slide2_label)
        self.slider2 = QtWidgets.QSlider(self.centralwidget)
        self.slider2.setMaximum(100)
        self.slider2.setOrientation(QtCore.Qt.Horizontal)
        self.slider2.setObjectName("slider2")
        self.horizontalLayout.addWidget(self.slider2)
        self.horizontalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(128, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_2.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem5)
        self.comboBox_comp2 = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_comp2.setFont(font)
        self.comboBox_comp2.setObjectName("comboBox_comp2")
        self.comboBox_comp2.addItem("")
        self.comboBox_comp2.addItem("")
        self.comboBox_comp2.addItem("")
        self.comboBox_comp2.addItem("")
        self.comboBox_comp2.addItem("")
        self.comboBox_comp2.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_comp2)
        self.verticalLayout_8.addLayout(self.formLayout_2)
        self.verticalLayout_13.addLayout(self.verticalLayout_8)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_13.addItem(spacerItem6)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        self.verticalLayout_15.addLayout(self.verticalLayout_14)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_15.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_15.addItem(spacerItem8)
        self.verticalLayout_16.addLayout(self.verticalLayout_15)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_16.addItem(spacerItem9)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_16.addItem(spacerItem10)
        self.verticalLayout_17.addLayout(self.verticalLayout_16)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_17.addItem(spacerItem11)
        self.verticalLayout_18.addLayout(self.verticalLayout_17)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_out1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_out1.setFont(font)
        self.label_out1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_out1.setObjectName("label_out1")
        self.verticalLayout_5.addWidget(self.label_out1)
        self.scrollArea_out2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_out2.setWidgetResizable(True)
        self.scrollArea_out2.setObjectName("scrollArea_out2")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 300, 319))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.view_out1 = ImageView(self.scrollAreaWidgetContents_6)
        self.view_out1.setObjectName("view_out1")
        self.gridLayout_5.addWidget(self.view_out1, 0, 0, 1, 1)
        self.scrollArea_out2.setWidget(self.scrollAreaWidgetContents_6)
        self.verticalLayout_5.addWidget(self.scrollArea_out2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_out2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_out2.setFont(font)
        self.label_out2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_out2.setObjectName("label_out2")
        self.verticalLayout_6.addWidget(self.label_out2)
        self.scrollArea_out1 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_out1.setWidgetResizable(True)
        self.scrollArea_out1.setObjectName("scrollArea_out1")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 299, 319))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.view_out2 = ImageView(self.scrollAreaWidgetContents_5)
        self.view_out2.setObjectName("view_out2")
        self.gridLayout_6.addWidget(self.view_out2, 0, 0, 1, 1)
        self.scrollArea_out1.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_6.addWidget(self.scrollArea_out1)
        self.horizontalLayout_8.addLayout(self.verticalLayout_6)
        self.verticalLayout_18.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3.addLayout(self.verticalLayout_18)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1268, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Img1 = QtWidgets.QAction(MainWindow)
        self.actionOpen_Img1.setObjectName("actionOpen_Img1")
        self.actionMagnitude = QtWidgets.QAction(MainWindow)
        self.actionMagnitude.setObjectName("actionMagnitude")
        self.actionPhase = QtWidgets.QAction(MainWindow)
        self.actionPhase.setObjectName("actionPhase")
        self.actionReal = QtWidgets.QAction(MainWindow)
        self.actionReal.setObjectName("actionReal")
        self.actionImaginary = QtWidgets.QAction(MainWindow)
        self.actionImaginary.setObjectName("actionImaginary")
        self.actionUniform_Magnitude = QtWidgets.QAction(MainWindow)
        self.actionUniform_Magnitude.setObjectName("actionUniform_Magnitude")
        self.actionUniform_Phase = QtWidgets.QAction(MainWindow)
        self.actionUniform_Phase.setObjectName("actionUniform_Phase")
        self.actionMagnitude_2 = QtWidgets.QAction(MainWindow)
        self.actionMagnitude_2.setObjectName("actionMagnitude_2")
        self.actionPhase_2 = QtWidgets.QAction(MainWindow)
        self.actionPhase_2.setObjectName("actionPhase_2")
        self.actionReal_2 = QtWidgets.QAction(MainWindow)
        self.actionReal_2.setObjectName("actionReal_2")
        self.actionImaginary_2 = QtWidgets.QAction(MainWindow)
        self.actionImaginary_2.setObjectName("actionImaginary_2")
        self.actionUniform_Magnitude_2 = QtWidgets.QAction(MainWindow)
        self.actionUniform_Magnitude_2.setObjectName("actionUniform_Magnitude_2")
        self.actionUniform_Phase_2 = QtWidgets.QAction(MainWindow)
        self.actionUniform_Phase_2.setObjectName("actionUniform_Phase_2")
        self.actionMagnitude_3 = QtWidgets.QAction(MainWindow)
        self.actionMagnitude_3.setObjectName("actionMagnitude_3")
        self.actionphase = QtWidgets.QAction(MainWindow)
        self.actionphase.setObjectName("actionphase")
        self.actionReal_3 = QtWidgets.QAction(MainWindow)
        self.actionReal_3.setObjectName("actionReal_3")
        self.actionImaginary_3 = QtWidgets.QAction(MainWindow)
        self.actionImaginary_3.setObjectName("actionImaginary_3")
        self.actionUniform_Magnitude_3 = QtWidgets.QAction(MainWindow)
        self.actionUniform_Magnitude_3.setObjectName("actionUniform_Magnitude_3")
        self.actionUniform_Phase_3 = QtWidgets.QAction(MainWindow)
        self.actionUniform_Phase_3.setObjectName("actionUniform_Phase_3")
        self.actionMagnitude_4 = QtWidgets.QAction(MainWindow)
        self.actionMagnitude_4.setObjectName("actionMagnitude_4")
        self.actionPhase_3 = QtWidgets.QAction(MainWindow)
        self.actionPhase_3.setObjectName("actionPhase_3")
        self.actionReal_4 = QtWidgets.QAction(MainWindow)
        self.actionReal_4.setObjectName("actionReal_4")
        self.actionImaginary_4 = QtWidgets.QAction(MainWindow)
        self.actionImaginary_4.setObjectName("actionImaginary_4")
        self.actionUniform_Magnitude_4 = QtWidgets.QAction(MainWindow)
        self.actionUniform_Magnitude_4.setObjectName("actionUniform_Magnitude_4")
        self.actionUniform_Phase_4 = QtWidgets.QAction(MainWindow)
        self.actionUniform_Phase_4.setObjectName("actionUniform_Phase_4")
        self.actionOutput_1 = QtWidgets.QAction(MainWindow)
        self.actionOutput_1.setObjectName("actionOutput_1")
        self.actionOutput_2 = QtWidgets.QAction(MainWindow)
        self.actionOutput_2.setObjectName("actionOutput_2")
        self.actionOpen_Img2 = QtWidgets.QAction(MainWindow)
        self.actionOpen_Img2.setObjectName("actionOpen_Img2")
        self.menuFile.addAction(self.actionOpen_Img1)
        self.menuFile.addAction(self.actionOpen_Img2)
        self.menubar.addAction(self.menuFile.menuAction())

        self.view_img1.ui.histogram.hide()
        self.view_img1.ui.roiBtn.hide()
        self.view_img1.ui.menuBtn.hide()
        self.view_img1.ui.roiPlot.hide()
        ####################################
        self.view_img2.ui.histogram.hide()
        self.view_img2.ui.roiBtn.hide()
        self.view_img2.ui.menuBtn.hide()
        self.view_img2.ui.roiPlot.hide()
        ####################################
        self.view_comp1.ui.histogram.hide()
        self.view_comp1.ui.roiBtn.hide()
        self.view_comp1.ui.menuBtn.hide()
        self.view_comp1.ui.roiPlot.hide()
        ###################################
        self.view_comp2.ui.histogram.hide()
        self.view_comp2.ui.roiBtn.hide()
        self.view_comp2.ui.menuBtn.hide()
        self.view_comp2.ui.roiPlot.hide()
        ####################################
        self.view_out1.ui.histogram.hide()
        self.view_out1.ui.roiBtn.hide()
        self.view_out1.ui.menuBtn.hide()
        self.view_out1.ui.roiPlot.hide()
        ##################################
        self.view_out2.ui.histogram.hide()
        self.view_out2.ui.roiBtn.hide()
        self.view_out2.ui.menuBtn.hide()
        self.view_out2.ui.roiPlot.hide()

        self.retranslateUi(MainWindow)
        self.img1_comp.setCurrentIndex(0)
        self.img2_comp.setCurrentIndex(0)
        self.comboBox_out.setCurrentIndex(-1)
        self.comboBox1_img.setCurrentIndex(-1)
        self.comboBox_comp1.setCurrentIndex(-1)
        self.comboBox2_img.setCurrentIndex(-1)
        self.comboBox_comp2.setCurrentIndex(-1)
        self.Slider1.sliderMoved['int'].connect(self.slide1_label.setNum)
        self.slider2.sliderMoved['int'].connect(self.slide2_label.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Mixer"))
        self.label_img1.setText(_translate("MainWindow", "Image 1"))
        self.label_img2.setText(_translate("MainWindow", "Image 2"))
        self.img1_comp.setAccessibleName(_translate("MainWindow", "<html><head/><body><p>Img1 Comp.</p></body></html>"))
        self.img1_comp.setItemText(0, _translate("MainWindow", "Mag. , Phase , Real , Imag. , Uni. Mag., ...."))
        self.img1_comp.setItemText(2, _translate("MainWindow", "Phase"))
        self.img1_comp.setItemText(3, _translate("MainWindow", "Real"))
        self.img1_comp.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.img1_comp.setItemText(5, _translate("MainWindow", "Uniform Magnitude"))
        self.img1_comp.setItemText(6, _translate("MainWindow", "Uniform Phase"))
        self.img2_comp.setAccessibleName(_translate("MainWindow", "<html><head/><body><p>Img1 Comp.</p></body></html>"))
        self.img2_comp.setItemText(0, _translate("MainWindow", "Mag. , Phase , Real , Imag. , Uni. Mag., ...."))
        self.img2_comp.setItemText(2, _translate("MainWindow", "Phase"))
        self.img2_comp.setItemText(3, _translate("MainWindow", "Real"))
        self.img2_comp.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.img2_comp.setItemText(5, _translate("MainWindow", "Uniform Magnitude"))
        self.img2_comp.setItemText(6, _translate("MainWindow", "Uniform Phase"))
        self.label_mixer.setText(_translate("MainWindow", "Mixer Output to :"))
        self.comboBox_out.setItemText(0, _translate("MainWindow", "Output 1"))
        self.comboBox_out.setItemText(1, _translate("MainWindow", "Output 2"))
        self.label_comp1.setText(_translate("MainWindow", "Component 1 :"))
        self.comboBox1_img.setItemText(0, _translate("MainWindow", "Image 1"))
        self.comboBox1_img.setItemText(1, _translate("MainWindow", "Image 2"))
        self.slide1_label.setText(_translate("MainWindow", "0%"))
        self.comboBox_comp1.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.comboBox_comp1.setItemText(1, _translate("MainWindow", "Phase"))
        self.comboBox_comp1.setItemText(2, _translate("MainWindow", "Real"))
        self.comboBox_comp1.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.comboBox_comp1.setItemText(4, _translate("MainWindow", "Uniform Phase"))
        self.comboBox_comp1.setItemText(5, _translate("MainWindow", "Uniform Magnitude"))
        self.label_comp2.setText(_translate("MainWindow", "Component 2 :"))
        self.comboBox2_img.setItemText(0, _translate("MainWindow", "Image 1"))
        self.comboBox2_img.setItemText(1, _translate("MainWindow", "Image 2"))
        self.slide2_label.setText(_translate("MainWindow", "0%"))
        self.comboBox_comp2.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.comboBox_comp2.setItemText(1, _translate("MainWindow", "Phase"))
        self.comboBox_comp2.setItemText(2, _translate("MainWindow", "Real"))
        self.comboBox_comp2.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.comboBox_comp2.setItemText(4, _translate("MainWindow", "Uniform Phase"))
        self.comboBox_comp2.setItemText(5, _translate("MainWindow", "Uniform Magnitude"))
        self.label_out1.setText(_translate("MainWindow", "Output 1"))
        self.label_out2.setText(_translate("MainWindow", "Output 2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_Img1.setText(_translate("MainWindow", "Open  Image 1"))
        self.actionMagnitude.setText(_translate("MainWindow", "Magnitude"))
        self.actionPhase.setText(_translate("MainWindow", "Phase"))
        self.actionReal.setText(_translate("MainWindow", "Real"))
        self.actionImaginary.setText(_translate("MainWindow", "Imaginary"))
        self.actionUniform_Magnitude.setText(_translate("MainWindow", "Uniform Magnitude"))
        self.actionUniform_Phase.setText(_translate("MainWindow", "Uniform Phase"))
        self.actionMagnitude_2.setText(_translate("MainWindow", "Magnitude"))
        self.actionPhase_2.setText(_translate("MainWindow", "Phase"))
        self.actionReal_2.setText(_translate("MainWindow", "Real"))
        self.actionImaginary_2.setText(_translate("MainWindow", "Imaginary"))
        self.actionUniform_Magnitude_2.setText(_translate("MainWindow", "Uniform Magnitude"))
        self.actionUniform_Phase_2.setText(_translate("MainWindow", "Uniform Phase"))
        self.actionMagnitude_3.setText(_translate("MainWindow", "Magnitude"))
        self.actionphase.setText(_translate("MainWindow", "phase"))
        self.actionReal_3.setText(_translate("MainWindow", "Real"))
        self.actionImaginary_3.setText(_translate("MainWindow", "Imaginary"))
        self.actionUniform_Magnitude_3.setText(_translate("MainWindow", "Uniform Magnitude"))
        self.actionUniform_Phase_3.setText(_translate("MainWindow", "Uniform Phase"))
        self.actionMagnitude_4.setText(_translate("MainWindow", "Magnitude"))
        self.actionPhase_3.setText(_translate("MainWindow", "Phase"))
        self.actionReal_4.setText(_translate("MainWindow", "Real"))
        self.actionImaginary_4.setText(_translate("MainWindow", "Imaginary"))
        self.actionUniform_Magnitude_4.setText(_translate("MainWindow", "Uniform Magnitude"))
        self.actionUniform_Phase_4.setText(_translate("MainWindow", "Uniform Phase"))
        self.actionOutput_1.setText(_translate("MainWindow", "Output 1"))
        self.actionOutput_2.setText(_translate("MainWindow", "Output 2"))
        self.actionOpen_Img2.setText(_translate("MainWindow", "Open Image 2"))
from pyqtgraph import ImageView


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
